### ISSUE TITLE
Compatibility problem with Das schwarze Auge/The Dark Eye (5th Edition) System

### ISSUE THREAD

**Issue by vt-tom** [zeel01/monarch#15] opened 2021-12-22 13:41 UTC
The System Das schwarze Auge/The Dark Eye (5th Edition) is actually not compatible with the sheets. But it would be great if you can make it work, because monarch looks great.

Deck Sheet (works):
![grafik](https://user-images.githubusercontent.com/80099175/147101485-a8e48da7-865d-4afc-9ae4-bca2d7712358.png)

Hand Sheet (not working):
![grafik](https://user-images.githubusercontent.com/80099175/147101532-190ea40b-188b-4bf8-96d4-3ab895048b11.png)

Stack Sheet (working):
![grafik](https://user-images.githubusercontent.com/80099175/147101706-720eba8c-b664-4ce2-b473-f4173c3fcbf9.png)

Also not working: Drag and Drop between the sheets, but i dont know if this is system specific

**Comment by zeel01** [comment] 2021-12-22 15:41
There is a very high chance that the issues are caused by leaky CSS on the part of the system, I'll give it a look, but I would suggest also opening an issue with the system regarding this as I won't have time to check on it right away, and in similar cases it was the system causing the issue.

**Comment by vt-tom** [comment] 2021-12-22 16:02
No problem, I will also contact the system developer.

**Comment by Plushtoast** [comment] 2021-12-22 16:56
I ll solve it on the Game System side

**Comment by Plushtoast** [comment] 2021-12-31 09:57
The issue should be gone once this ticket is closed:
https://github.com/Plushtoast/dsa5-foundryVTT/issues/784

Next patch of the system in january.

**Comment by zeel01** [comment] 2022-02-03 07:55
Closed via: https://github.com/Plushtoast/dsa5-foundryVTT/issues/784

**Closed by zeel01** 2022-02-03 07:55 UTC
Labels: bug
